### ISSUE TITLE
[Suggestion] Allowing to draw from multiple different Docker instances for the Docker API.

### ISSUE THREAD

**Issue by InspireToCode** [callmekory/nezuko#2]
Currently, you can only set this to draw from one instance's API at a time, though if you run multiple VMs that all run docker and you'd like to gather the info and present it for all VMs that run Docker.

Maybe have a + symbol below the Host but above the Save, where when you click it it would create a new "Host" line, with a - beside it (if clicked will remove the line).

**Comment by senpaiSubby** [comment]
This is something that I would add into the //config command to begin with and later add it into the UI since ATM it's allot faster to get it handled command wise than ui wise
