### ISSUE TITLE
[Suggestion] Rclone ls permissions per remote basis

### ISSUE THREAD

**Issue by InspireToCode** [callmekory/nezuko#3]
It'd be cool to change permissions of what role/users can see which specific remotes you have available in rclone.

**Comment by senpaiSubby** [comment]
This is a good idea. I was thinking of implementing a command that you can lock specific command usages. Ex //lock <user> drive ls personalDrive

**Comment by senpaiSubby** [comment]
Also maybe some flags for whether to lock per group or user

**Comment by InspireToCode** [comment]
Sounds good, when adding to the webUI you can add a drop down for picking which roles are locked.

**Comment by senpaiSubby** [comment]
I added the a new commad name `cmd` you can use it to lock specific command usages or entire command. Check out the help command to see more info on it!
